#!/bin/bash
# If the directories were numbered, a simple find could be used to build ;-)

CONTAINERS=(fedora-rdo-base cinder glance/glance-base glance/glance-api glance/glance-registry keystone mariadb rabbitmq)

for IMAGE in ${CONTAINERS[@]}; do
        echo "Building $IMAGE"
        pushd .
        cd ${IMAGE}
        ./build
        popd
done
